services:
    postgres:
        image: postgres:16-alpine
        container_name: sentinel-postgres
        restart: unless-stopped
        ports:
            - '${POSTGRES_PORT}:${POSTGRES_PORT}'
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        volumes:
            - postgres_data:/var/lib/postgresql/data
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -U sentinel -d sentinel_db']
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 30s
        networks:
            - sentinel-network

    mongodb:
        image: mongo:7
        container_name: sentinel-mongodb
        restart: unless-stopped
        ports:
            - '27017:27017'
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
            MONGO_INITDB_DATABASE: ${MONGO_DB}
        volumes:
            - mongodb_data:/data/db
        healthcheck:
            test: ['CMD', 'mongosh', '--eval', "db.adminCommand('ping')"]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 30s
        networks:
            - sentinel-network

    rabbitmq:
        image: rabbitmq:3.13-management-alpine
        container_name: sentinel-rabbitmq
        restart: unless-stopped
        ports:
            - '5672:5672'
            - '15672:15672'
        environment:
            RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
            RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
            RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_VHOST}
        volumes:
            - rabbitmq_data:/var/lib/rabbitmq
        healthcheck:
            test: ['CMD', 'rabbitmq-diagnostics', '-q', 'ping']
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 30s
        networks:
            - sentinel-network

volumes:
    postgres_data:
        driver: local
    mongodb_data:
        driver: local
    rabbitmq_data:
        driver: local

networks:
    sentinel-network:
        driver: bridge
        name: sentinel-network
