global:
    scrape_interval: 15s

scrape_configs:
    - job_name: 'prometheus'
      static_configs:
          - targets: ['localhost:9090']

    - job_name: 'sentinel-gateway'
      metrics_path: '/api/metrics'
      static_configs:
          - targets: ['host.docker.internal:3000']

    - job_name: 'sentinel-log-processor'
      metrics_path: '/metrics'
      static_configs:
          - targets: ['host.docker.internal:3001']

    - job_name: 'sentinel-ai-service'
      metrics_path: '/metrics'
      static_configs:
          - targets: ['host.docker.internal:3002']

    - job_name: 'sentinel-notification-service'
      metrics_path: '/metrics'
      static_configs:
          - targets: ['host.docker.internal:3003']
