import { Injectable, Logger, OnModuleInit } from '@nestjs/common'
import { ConfigService } from '@nestjs/config'
import { ENV_VARS } from '@sentinel-supreme/shared'
import { SendNotificationDto } from '@sentinel-supreme/shared/server'
import * as nodemailer from 'nodemailer'

@Injectable()
export class EmailService implements OnModuleInit {
	private readonly logger = new Logger(EmailService.name)
	private transporter!: nodemailer.Transporter

	constructor(private readonly config: ConfigService) {}

	async onModuleInit() {
		const host = this.config.getOrThrow<string>(ENV_VARS.SMTP_HOST)
		const port = this.config.getOrThrow<number>(ENV_VARS.SMTP_PORT)
		const user = this.config.getOrThrow<string>(ENV_VARS.SMTP_USER)
		const pass = this.config.getOrThrow<string>(ENV_VARS.SMTP_PASS)

		if (!user || !pass) {
			this.logger.error('❌ SMTP credentials missing in ConfigService!')
			return
		}

		this.transporter = nodemailer.createTransport({
			host: host,
			port: port,
			secure: port === 465,
			auth: {
				user,
				pass
			}
		})

		try {
			await this.transporter.verify()
			this.logger.log('✅ SMTP connection established successfully via ConfigService')
		} catch (error) {
			this.logger.error('❌ SMTP connection failed', error)
		}
	}

	async sendCriticalAlert(data: SendNotificationDto) {
		const { title, message, severity } = data

		const mailOptions = {
			from: '"Sentinel Supreme 🛡️" <alerts@sentinel-supreme.io>',
			to: 'admin@sentinel-supreme.io',
			subject: `[${severity.toUpperCase()}] ${title}`,
			html: `
				<div style="font-family: sans-serif; border: 1px solid #e11d48; padding: 20px; border-radius: 8px; max-width: 600px;">
				<h2 style="color: #e11d48; margin-top: 0;">🔥 Critical Alert Detected</h2>
				<div style="background-color: #fff1f2; border-left: 4px solid #e11d48; padding: 10px; margin-bottom: 20px;">
					<p style="margin: 0; font-weight: bold; color: #9f1239;">${title}</p>
				</div>
				<p><strong>Severity:</strong> <span style="color: #e11d48;">${severity}</span></p>
				<p><strong>Timestamp:</strong> ${new Date().toLocaleString()}</p>
				<hr style="border: none; border-top: 1px solid #e2e8f0; margin: 20px 0;" />
				<p style="white-space: pre-wrap;">${message}</p>
				<br />
				<p style="font-size: 12px; color: #64748b;">
					This email was generated by Sentinel-Supreme log processing engine because a critical rule was triggered.
				</p>
				</div>
			`
		}

		try {
			const info = await this.transporter.sendMail(mailOptions)
			this.logger.log(`✉️ Email sent: ${info.messageId}`)

			const previewUrl = nodemailer.getTestMessageUrl(info)

			if (previewUrl) {
				this.logger.log(`🔗 Preview URL: ${previewUrl}`)
			}

			return info
		} catch (error) {
			this.logger.error('❌ Error sending email', error)
			throw error
		}
	}
}
