export const LOG_SERVICE = 'LOG_SERVICE'

export const QUEUES = {
	LOG_QUEUE: 'log_queue'
}

export const LOG_PATTERNS = {
	NEW_LOG: 'log_message'
}

export const ENV_VARS = {
	POSTGRES_USER: 'POSTGRES_USER',
	POSTGRES_PASSWORD: 'POSTGRES_PASSWORD',
	POSTGRES_DB: 'POSTGRES_DB',
	POSTGRES_PORT: 'POSTGRES_PORT',
	JWT_SECRET: 'JWT_SECRET',
	JWT_EXPIRATION_IN_SECONDS: 'JWT_EXPIRATION_IN_SECONDS',
	MONGO_USER: 'MONGO_USER',
	MONGO_PASSWORD: 'MONGO_PASSWORD',
	MONGO_PORT: 'MONGO_PORT',
	MONGO_DB: 'MONGO_DB',
	RABBITMQ_USER: 'RABBITMQ_USER',
	RABBITMQ_PASSWORD: 'RABBITMQ_PASSWORD',
	RABBITMQ_PORT: 'RABBITMQ_PORT',
	RABBITMQ_VHOST: 'RABBITMQ_VHOST'
}

export const DL_CONFIG = {
	DLX_HEADER: 'x-dead-letter-exchange',
	DL_ROUTING_KEY_HEADER: 'x-dead-letter-routing-key',
	DLX_EXCHANGE: 'log_dlx',
	DLQ_NAME: 'log_queue_dead_letters',
	DL_ROUTING_KEY: 'log_dead_letter_key'
}

export const JWT_FALLBACK_SECRET = 'fallback_secret'
