export const PROCESSOR_CLIENT = 'PROCESSOR_CLIENT'
export const ALERTS_CLIENT = 'ALERTS_CLIENT'
export const NOTIFICATIONS_CLIENT = 'NOTIFICATIONS_CLIENT'
export const AI_ANALYSIS_CLIENT = 'AI_ANALYSIS_CLIENT'
